export const WORDS = {
    'A': [
        'ABÁLT', 'ABBAN', 'ABBÓL', 'ABCÚG', 'ABLAK', 'ABRAK', 'ACHÁT', 'ADDIG', 'ADOMA', 'ADOTT', 'ADÓÍV', 'ADÓZÓ', 'ADUTT', 'AFELÉ',
        'AFFÉR', 'AFGÁN', 'AGÁVÉ', 'AGGAT', 'AGORA', 'AGRÁR', 'AGUTI', 'AGYAG', 'AGYAL', 'AGYAR', 'AGYON', 'AHÁNY', 'AHHOZ', 'AHOGY',
        'AHOVA', 'AHOVÁ', 'AJÁNL', 'AJÓKA', 'AKCIÓ', 'AKKÁD', 'AKKOR', 'AKNÁS', 'AKNÁZ', 'AKRIL', 'AKTÁS', 'AKTÁZ', 'AKTÍV', 'AKTUS',
        'ALAKI', 'ALAKÚ', 'ALANT', 'ALANY', 'ALATT', 'ALÁÁS', 'ALÁBB', 'ALÁÍR', 'ALÁLŐ', 'ALÁÜL', 'ALBÁN', 'ALBUM', 'ALCÍM', 'ALÉLT',
        'ALFAJ', 'ALFÉL', 'ALGÁS', 'ALHAS', 'ALIBI', 'ALJAS', 'ALKAR', 'ALKAT', 'ALKOT', 'ALKÓV', 'ALLŰR', 'ALMÁS', 'ALMOZ', 'ALPIN',
        'ALSÓS', 'ALTAT', 'ALULI', 'ALVAD', 'ALVÁS', 'ALVÁZ', 'ALVÉG', 'AMELY', 'AMINT', 'AMIRE', 'AMODA', 'AMORF', 'AMOTT', 'AMŐBA',
        'AMPER', 'AMÚGY', 'ANCÚG', 'ANGOL', 'ANKÉT', 'ANNAK', 'ANNÁL', 'ANION', 'ANNÁL', 'ANNYI', 'ANTIK', 'ANYAG', 'ANYAI', 'ANYÁS',
        'ANYÓS', 'ANYUS', 'AORTA', 'APÁCA', 'APACS', 'APÁLY', 'APONÉ', 'APÓKA', 'APRÍT', 'APRÓD', 'APRÓZ', 'APUCI', 'APUKA', 'ARANY',
        'ARASZ', 'ARATÓ', 'ARÁMI', 'ARÁNY', 'ARCÉL', 'ARÉNA', 'ARGON', 'AROMA', 'ARRÓL', 'ARZÉN', 'ASSZÓ', 'ASZAL', 'ASZAT', 'ASZIK',
        'ASSZÓ', 'ATKÁS', 'ATOLL', 'ATOMI', 'ATTÓL', 'ATYAI', 'ATYUS', 'AUDIT', 'AUDIO', 'AUDIT', 'AUGUR', 'AUTÓS', 'AVAGY', 'AVATÓ',
        'AVÍTT', 'AVULT', 'AZÉRT', 'AZNAP', 'AZÓTA', 'AZTÁN', 'AZTÉK', 'AZZAL', 'AZSÚR'
    ],
    'Á': [
        'ÁCSOL', 'ÁGENS', 'ÁGYAS', 'ÁGYAZ', 'ÁGYÁS', 'ÁGYÉK', 'ÁGYÚS', 'ÁGYÚZ', 'ÁJULT', 'ÁLARC', 'ÁLCÁZ', 'ÁLDÁS', 'ÁLDOZ', 'ÁLHÍR',
        'ÁLLAG', 'ÁLLAM', 'ÁLLAT', 'ÁLLÁS', 'ÁLLÍT', 'ÁLMOS', 'ÁLNÉV', 'ÁLNOK', 'ÁLTAL', 'ÁLTAT', 'ÁMBÁR', 'ÁMBRA', 'ÁNIZS', 'ÁPOLÓ',
        'ÁPOLT', 'ÁRADÓ', 'ÁRBOC', 'ÁRGUS', 'ÁRKÁD', 'ÁRKOL', 'ÁRLAP', 'ÁRRÉS', 'ÁRSÁV', 'ÁRTÁS', 'ÁRTÉR', 'ÁRUDA', 'ÁRULÓ', 'ÁRVÍZ',
        'ÁSPIS', 'ÁSZKA', 'ÁTADÓ', 'ÁTALL', 'ÁTÁLL', 'ÁTBÖK', 'ÁTDOB', 'ÁTDÖF', 'ÁTDŐL', 'ÁTDUG', 'ÁTEJT', 'ÁTFED', 'ÁTFEJ', 'ÁTFÉR',
        'ÁTFOG', 'ÁTFON', 'ÁTFŐZ', 'ÁTFUT', 'ÁTFÚJ', 'ÁTFÚR', 'ÁTFŰT', 'ÁTFŰZ', 'ÁTHAT', 'ÁTHÁG', 'ÁTHÍV', 'ÁTHOZ', 'ÁTHÚZ', 'ÁTHŰL',
        'ÁTHŰT', 'ÁTJÁR', 'ÁTJÖN', 'ÁTJUT', 'ÁTKEL', 'ÁTKÉR', 'ÁTKOS', 'ÁTKOZ', 'ÁTKÖT', 'ÁTLAG', 'ÁTLÁT', 'ÁTLÉP', 'ÁTLÓG', 'ÁTLÓS',
        'ÁTLÖK', 'ÁTMOS', 'ÁTNÉZ', 'ÁTOLT', 'ÁTÖLT', 'ÁTÖNT', 'ÁTRAK', 'ÁTRÁG', 'ÁTRÁZ', 'ÁTSÜL', 'ÁTSÜT', 'ÁTSZŐ', 'ÁTTÉR', 'ÁTTOL',
        'ÁTTÖR', 'ÁTÜTŐ', 'ÁTVÁG', 'ÁTVER', 'ÁTVET', 'ÁTVON', 'ÁZOTT', 'ÁZTAT', 'ÁZSIÓ'
    ],
    'B': [
        'BABÉR', 'BABOS', 'BADAR', 'BAJOR', 'BAJOS', 'BALEK', 'BALGA', 'BALHÉ', 'BALOS', 'BALTA', 'BALUL', 'BAMBA', 'BANÁN', 'BANDA',
        'BANKI', 'BANKÓ', 'BANYA', 'BARÁT', 'BARKA', 'BARKÓ', 'BARNA', 'BAROM', 'BASZK', 'BATÁR', 'BATIK', 'BATYU', 'BAZÁR', 'BÁBOS',
        'BÁCSI', 'BÁDOG', 'BÁJOS', 'BÁLÁS', 'BÁLÁZ', 'BÁLNA', 'BÁMUL', 'BÁNAT', 'BÁNÁS', 'BÁNIK', 'BÁNTÓ', 'BÁNYA', 'BÁRCA', 'BÁRKA',
        'BÁRKI', 'BÁRMI', 'BÁRÓI', 'BÁTOR', 'BÁZIS', 'BEÁLL', 'BEDOB', 'BEDÖF', 'BEDŐL', 'BEDUG', 'BEEJT', 'BEFAL', 'BEFED', 'BEFÉR',
        'BEFOG', 'BEFON', 'BEFÖD', 'BEFŐZ', 'BEFUT', 'BEFÚJ', 'BEFÚR', 'BEFŰT', 'BEFŰZ', 'BEHÍV', 'BEHOZ', 'BEHÚZ', 'BEHŰT', 'BEINT',
        'BEJÁR', 'BEJÖN', 'BEJUT', 'BEKAP', 'BEKEN', 'BEKÉR', 'BEKÖP', 'BEKÖT', 'BELAK', 'BELÁT', 'BELEP', 'BELES', 'BELÉP', 'BELGA',
        'BELOP', 'BELÓG', 'BELÖK', 'BELSŐ', 'BELÜL', 'BEMAR', 'BEMÉR', 'BENDŐ', 'BENÉZ', 'BENNE', 'BENSŐ', 'BENTI', 'BEOLT', 'BEÖLT',
        'BEÖNT', 'BERAK', 'BERÁG', 'BERÁZ', 'BEREK', 'BERÚG', 'BESÓZ', 'BESÚG', 'BESÜT', 'BESZŐ', 'BETEG', 'BETÉP', 'BETÉR', 'BETÉT',
        'BETOL', 'BETON', 'BETÖM', 'BETÖR', 'BETUD', 'BETŰR', 'BETŰZ', 'BEVÁG', 'BEVÁR', 'BEVER', 'BEVET', 'BEVÉD', 'BEVÉS', 'BEVON',
        'BEZÁR', 'BEZÚZ', 'BÉGET', 'BÉKÉS', 'BÉKÍT', 'BÉKÜL', 'BÉLEL', 'BÉLES', 'BÉLÉS', 'BÉNÍT', 'BÉREL', 'BÉRES', 'BÉRLŐ', 'BICAJ',
        'BICEG', 'BIGYÓ', 'BIMBÓ', 'BINGÓ', 'BIRKA', 'BIROK', 'BIZSU', 'BÍBIC', 'BÍBOR', 'BÍRÁL', 'BÍRÁS', 'BÍRÓI', 'BÍZIK', 'BLATT',
        'BLIKK', 'BLOKK', 'BLÖFF', 'BODZA', 'BOGÁR', 'BOGOZ', 'BOGYÓ', 'BOHÉM', 'BOHÓC', 'BOKOR', 'BOKSZ', 'BOLHA', 'BOLTI', 'BOLYH',
        'BOMBA', 'BONTÓ', 'BORDA', 'BORDÓ', 'BORÍT', 'BORJÚ', 'BORKŐ', 'BOROS', 'BORSÓ', 'BORUL', 'BORÚS', 'BOTOR', 'BOTOS', 'BOTOZ',
        'BOXER', 'BOZÓT', 'BÓDÍT', 'BÓDUL', 'BÓKOL', 'BÓVLI', 'BÖDÖN', 'BÖFÖG', 'BÖGRE', 'BÖJTI', 'BÖKÉS', 'BÖKÖD', 'BÖLCS', 'BÖRZE',
        'BŐGÉS', 'BŐGŐS', 'BŐRKE', 'BŐRÖS', 'BŐRÖV', 'BŐRÖZ', 'BŐSÉG', 'BŐVEN', 'BŐVÍT', 'BŐVÜL', 'BRAVÓ', 'BRIÓS', 'BRONZ', 'BROSS',
        'BUCKA', 'BUGYI', 'BUKÁS', 'BUKIK', 'BUKSI', 'BUKTA', 'BULLA', 'BUNDA', 'BUNKÓ', 'BUNYÓ', 'BUROK', 'BUSÁS', 'BUTÁN', 'BUTIK',
        'BUTÍT', 'BUTUL', 'BUTUS', 'BUXUS', 'BUZGÓ', 'BUZOG', 'BÚBOS', 'BÚCSÚ', 'BÚGAT', 'BÚGÁS', 'BÚJÁS', 'BÚJIK', 'BÚJÓS', 'BÚSÍT',
        'BÚSUL', 'BÚTOR', 'BÚVÁR', 'BÚZÁS', 'BÜDÖS', 'BÜRÖK', 'BŰBÁJ', 'BŰNÖS', 'BŰVÖS', 'BŰZÖS'
    ],
    'C': [
        'CAFAT', 'CAFKA', 'CANKÓ', 'CÁFOL', 'CEFRE', 'CELEB', 'CELLA', 'CENTI', 'CETLI', 'CÉGES', 'CÉGÉR', 'CÉKLA', 'CÉLOZ', 'CÉRNA',
        'CÉZÁR', 'CHIPS', 'CIBÁL', 'CICUS', 'CIDRI', 'CIFRA', 'CIKIS', 'CIKIZ', 'CIMET', 'CIMPA', 'CINKE', 'CIRKA', 'CIROK', 'CITÁL',
        'CIVIL', 'CÍVIS', 'CÍMER', 'CÍMEZ', 'CÍMKE', 'CÖLÖP', 'CÖVEK', 'CUCLI', 'CUDAR', 'CUKOR', 'CÚGOS', 'CSALI', 'CSALÓ', 'CSAPA',
        'CSAPÓ', 'CSATA', 'CSÁJA', 'CSÁKÓ', 'CSÁLÉ', 'CSÁVA', 'CSECS', 'CSEHÓ', 'CSEKK', 'CSEND', 'CSENG', 'CSEPP', 'CSERE', 'CSÉVE',
        'CSÉZA', 'CSIBE', 'CSIGA', 'CSIBE', 'CSIKK', 'CSIKÓ', 'CSILI', 'CSITT', 'CSÍNY', 'CSIPA', 'CSÍPŐ', 'CSÍRA', 'CSODA', 'CSOKI',
        'CSOMÓ', 'CSONK', 'CSONT', 'CSÓKA', 'CSÓRÓ', 'CSÓVA', 'CSÖCS', 'CSÖND', 'CSÖNG', 'CSÖPP', 'CSŐSZ', 'CSUHA', 'CSUHÉ', 'CSUKA',
        'CSUMA', 'CSUPA', 'CSÚCS', 'CSÜNG', 'CUCLI', 'CUDAR', 'CUKOR'
    ],
    'D': [
        'DACOL', 'DACOS', 'DADOG', 'DAFKE', 'DAGAD', 'DAJKA', 'DALIA', 'DALOL', 'DALOS', 'DALMŰ', 'DAMIL', 'DARAB', 'DARÁL', 'DARÓC',
        'DARTS', 'DARUS', 'DATÁL', 'DAUER', 'DÁCSA', 'DÁLIA', 'DÁRDA', 'DÁTUM', 'DECIS', 'DECIZ', 'DEKÁD', 'DELEJ', 'DELEL', 'DELTA',
        'DENIM', 'DERBI', 'DERES', 'DERÉK', 'DERÍT', 'DERÜL', 'DERŰS', 'DETTÓ', 'DÉKÁN', 'DÉMON', 'DÉNÁR', 'DÉVAJ', 'DÉZSA', 'DICSŐ',
        'DIÉTA', 'DILIS', 'DINGÓ', 'DINKA', 'DIÓDA', 'DIÓFA', 'DIVAT', 'DÍJAZ', 'DÍLER', 'DÍNÁR', 'DÍVIK', 'DÍZEL', 'DOBÁL', 'DOBÁS',
        'DOBOG', 'DOBOL', 'DOBOS', 'DOBOZ', 'DOGMA', 'DOHOG', 'DOHOS', 'DOLOG', 'DONGA', 'DONGÓ', 'DONNA', 'DONOR', 'DOSZT', 'DOTÁL',
        'DÓZIS', 'DÓZSE', 'DÖCÖG', 'DÖFÉS', 'DÖGÖS', 'DÖNGŐ', 'DÖNTŐ', 'DÖREJ', 'DÖRGŐ', 'DÖRÖG', 'DŐLÉS', 'DÖLYF', 'DRÁGA', 'DRÁMA',
        'DRUKK', 'DUDÁL', 'DUDÁS', 'DUDOR', 'DUDVA', 'DUETT', 'DUGÁS', 'DUGIG', 'DUGÓS', 'DUGUL', 'DUHAJ', 'DUKÁL', 'DUKÁT', 'DUMÁL',
        'DUMÁS', 'DUNDI', 'DUNNA', 'DUPLA', 'DURVA', 'DÚCOL', 'DÚDOL', 'DUSÍT', 'DÚSUL', 'DÚVAD', 'DÜHÍT', 'DÜHÖS', 'DZSEM', 'DZSIP',
        'DZSÚZ'
    ],
    'E': [
        'EBADÓ', 'EBBEN', 'EBBŐL', 'ECSET', 'EDDIG', 'EDÉNY', 'EDZÉS', 'EFELÉ', 'EGÉSZ', 'EGRES', 'EGYBE', 'EGYED', 'EGYEL', 'EGYEN',
        'EGYES', 'EGYÉB', 'EGYÉN', 'EGYIK', 'EGYKE', 'EGYRE', 'EHETŐ', 'EHHEZ', 'EJNYE', 'EJTÉS', 'EKKOR', 'ELADÓ', 'ELÁLL', 'ELBÍR',
        'ELBÍZ', 'ELBŐG', 'ELDOB', 'ELDŐL', 'ELDUG', 'ELEGY', 'ELEJE', 'ELEJT', 'ELEMI', 'ELEVE', 'ELÉBE', 'ELÉRT', 'ELFED', 'ELFÉR',
        'ELFOG', 'ELFŐZ', 'ELFUT', 'ELFÚJ', 'ELFÚL', 'ELHAL', 'ELHÍV', 'ELHOZ', 'ELHÚZ', 'ELHŰL', 'ELJÁR', 'ELJÖN', 'ELJUT', 'ELKAP',
        'ELKEL', 'ELKEN', 'ELKÖT', 'ELKEL', 'ELKÉR', 'ELKÖP', 'ELKÖT', 'ELLÁT', 'ELLEN', 'ELLEP', 'ELLES', 'ELLÉP', 'ELLÉS', 'ELLIK',
        'ELLOP', 'ELLÓG', 'ELLÖK', 'ELMAR', 'ELMÉR', 'ELMÉS', 'ELMOS', 'ELNÉZ', 'ELNÖK', 'ELNYŰ', 'ELOLD', 'ELOLT', 'ELÖNT', 'ELŐAD',
        'ELŐÁS', 'ELŐBB', 'ELŐÍR', 'ELŐKE', 'ELŐNY', 'ELŐRE', 'ELŐTT', 'ELŐZŐ', 'ELRAK', 'ELRÁG', 'ELRÁZ', 'ELRÚG', 'ELSÍR', 'ELSÓZ',
        'ELSŐS', 'ELSÜL', 'ELSÜT', 'ELTÁT', 'ELTÉP', 'ELTÉR', 'ELTOL', 'ELTÖM', 'ELTÖR', 'ELTŰR', 'ELUNT', 'ELÜTŐ', 'ELVAN', 'ELVÁG',
        'ELVÁR', 'ELVER', 'ELVET', 'ELVÉT', 'ELVHŰ', 'ELVON', 'ELZÁR', 'ELZÚG', 'EMBER', 'EMELŐ', 'EMELT', 'EMIDE', 'EMITT', 'EMÍGY',
        'EMLÉK', 'EMLÍT', 'EMLŐS', 'ENGED', 'ENNEK', 'ENNÉL', 'ENZIM', 'ENYÉM', 'ENYHE', 'ENNYI', 'EPEKŐ', 'EPIKA', 'EPOSZ', 'EPRES',
        'ERDEI', 'ERDŐS', 'EREDŐ', 'EREJŰ', 'ERESZ', 'ERÉLY', 'ERÉNY', 'ERIKA', 'ERJED', 'ERNYŐ', 'ERŐMŰ', 'ERRŐL', 'ESENG', 'ESETI',
        'ESÉLY', 'ESKET', 'ESZES', 'ESZIK', 'ESZME', 'ESSZÉ', 'ETETŐ', 'ETIKA', 'ETTŐL', 'EVEZŐ', 'EXTRA', 'EZRED', 'EZREN', 'EZRES',
        'EZÜST', 'EZZEL'
    ],
    'É': [
        'ÉBRED', 'ÉBREN', 'ÉDENI', 'ÉGÉSI', 'ÉGETŐ', 'ÉGETT', 'ÉGIEK', 'ÉGISZ', 'ÉGÖVI', 'ÉGTÁJ', 'ÉHBÉR', 'ÉHEZŐ', 'ÉHSÉG', 'ÉJFÉL',
        'ÉJJEL', 'ÉLÉNK', 'ÉLJEN', 'ÉLTES', 'ÉLTET', 'ÉLVEZ', 'ÉNKÉP', 'ÉPÍTŐ', 'ÉPPEN', 'ÉPSÉG', 'ÉPÜLŐ', 'ÉRCES', 'ÉRDEK', 'ÉRDEM',
        'ÉRDES', 'ÉRETT', 'ÉRFAL', 'ÉRINT', 'ÉRLEL', 'ÉRMES', 'ÉRPÁR', 'ÉRRÖG', 'ÉRSEK', 'ÉRTÉK', 'ÉRTÉS', 'ÉRVEL', 'ÉRZET', 'ÉRZÉK',
        'ÉRZÉS', 'ÉRZET', 'ÉSZAK', 'ÉTERI', 'ÉTKES', 'ÉTLAP', 'ÉTLEN', 'ÉVELŐ'
    ],
    'F': [
        'FACÉR', 'FAEKE', 'FAFAJ', 'FAGYI', 'FAGYÓ', 'FAHÁZ', 'FAHÉJ', 'FAJHŐ', 'FAJTA', 'FAJUL', 'FAKAD', 'FAKÉP', 'FAKÍR', 'FAKÍT',
        'FAKUL', 'FALAS', 'FALAT', 'FALAZ', 'FALÁB', 'FALÁS', 'FALÉC', 'FALKA', 'FARAG', 'FAROK', 'FAROL', 'FARTŐ', 'FASOR', 'FATER',
        'FAUNA', 'FAVÁZ', 'FAXOL', 'FAZÉK', 'FAZON', 'FÁCÁN', 'FÁJÁS', 'FÁJÓS', 'FÁRAÓ', 'FÁRAD', 'FÁSÍT', 'FÁSLI', 'FÁSUL', 'FÁTUM',
        'FÁZÁS', 'FÁZIK', 'FÁZIS', 'FÁZÓS', 'FECNI', 'FEDDŐ', 'FEDEZ', 'FEDÉL', 'FEDÉS', 'FEHÉR', 'FEJEL', 'FEJES', 'FEJÉK', 'FEJÉS',
        'FEJFA', 'FEKVŐ', 'FELAD', 'FELÁR', 'FELÁS', 'FELED', 'FELEL', 'FELES', 'FELEZ', 'FELÉG', 'FELÉL', 'FELÉR', 'FELHŐ', 'FELÍR',
        'FELLŐ', 'FELNŐ', 'FELŐL', 'FELRÓ', 'FELSŐ', 'FELÜL', 'FELÜT', 'FENÉK', 'FENÉS', 'FENOL', 'FENTI', 'FENYŐ', 'FERDE', 'FERTŐ',
        'FESTŐ', 'FÉKEZ', 'FÉKÚT', 'FÉLBE', 'FÉLÉV', 'FÉLIG', 'FÉLŐS', 'FÉLRE', 'FÉLSZ', 'FÉLTŐ', 'FÉMES', 'FÉREG', 'FÉRFI', 'FÉSÜL',
        'FÉTIS', 'FICAM', 'FICKÓ', 'FIKÁS', 'FIKÁZ', 'FILÉZ', 'FINIS', 'FINOM', 'FIOLA', 'FIÓKA', 'FIRKA', 'FIRMA', 'FITOS', 'FITTY',
        'FIVÉR', 'FIXÁL', 'FIZET', 'FLANC', 'FLEKK', 'FLÓRA', 'FLOTT', 'FLÖRT', 'FLUOR', 'FODOR', 'FOGAD', 'FOGAN', 'FOGAS', 'FOGAT',
        'FOGÁS', 'FOGDA', 'FOGKŐ', 'FOGÓS', 'FOGVA', 'FOGYÓ', 'FOJTÓ', 'FOKOS', 'FOKOZ', 'FOLYÓ', 'FONAL', 'FONAT', 'FONÁK', 'FONÁL',
        'FONÁS', 'FONDÜ', 'FORGÓ', 'FORMA', 'FOROG', 'FORRÓ', 'FOSÁS', 'FOSIK', 'FOTEL', 'FOTON', 'FOTÓS', 'FOTÓZ', 'FÓBIA', 'FÓLIA',
        'FÓRUM', 'FÖDÉM', 'FÖLDI', 'FÖLÖS', 'FÖLÖZ', 'FÖLSŐ', 'FÖLÜL', 'FÖNTI', 'FŐCÍM', 'FŐDÍJ', 'FŐFAL', 'FŐHŐS', 'FŐIGE', 'FŐLEG',
        'FŐNÉV', 'FŐNIX', 'FŐNÖK', 'FŐNÖZ', 'FŐPAP', 'FŐTÉR', 'FŐÚRI', 'FŐZET', 'FŐZÉS', 'FRAKK', 'FRANC', 'FRANK', 'FRÁSZ', 'FREON',
        'FRIGY', 'FRISS', 'FRONT', 'FUCCS', 'FUKAR', 'FÜGÉS', 'FÜGGŐ', 'FUGÁZ', 'FUNKY', 'FURAT', 'FUTAM', 'FUTÁR', 'FUTÁS', 'FUVAR',
        'FÚJÁS', 'FÚRAT', 'FÚRÁS', 'FÚRIA', 'FÚVÓS', 'FÚZIÓ', 'FÜGGŐ', 'FÜLEL', 'FÜLES', 'FÜLKE', 'FÜLTŐ', 'FÜRDŐ', 'FÜRGE', 'FÜRDŐ',
        'FÜRGE', 'FÜTYI', 'FÜTTY', 'FÜVES', 'FÜZET', 'FÜZÉR', 'FŰEVŐ', 'FŰLIK', 'FŰMAG', 'FŰTÉS', 'FŰZÁG', 'FŰZÉS', 'FŰZFA', 'FŰZŐS'
    ],
    'G': [
        'GAGYI', 'GALÁD', 'GALLY', 'GAMMA', 'GANAJ', 'GANÉJ', 'GARAS', 'GARAT', 'GARBÓ', 'GATYA', 'GAZDA', 'GAZOL', 'GAZOS', 'GÁGOG',
        'GÁLYA', 'GÁNCS', 'GÁRDA', 'GÁTLÓ', 'GÁTOL', 'GÁTŐR', 'GÁZLÓ', 'GÁZOL', 'GÁZOS', 'GÁZSI', 'GEKKÓ', 'GENNY', 'GERLE', 'GETTÓ',
        'GÉPEL', 'GÉPES', 'GÉPÍR', 'GICCS', 'GIPSZ', 'GITÁR', 'GLANC', 'GLETT', 'GLÉDA', 'GOFRI', 'GOLYÓ', 'GOMBA', 'GÓLEM', 'GÓLYA',
        'GÖDÖR', 'GÖRBE', 'GÖRCS', 'GÖRGŐ', 'GÖRÖG', 'GŐGÖS', 'GŐZÖL', 'GŐZÖS', 'GRAMM', 'GRIFF', 'GRILL', 'GRÓFI', 'GRUND', 'GUANÓ',
        'GULÁG', 'GULYA', 'GUMIZ', 'GUMÓS', 'GUPPI', 'GURÍT', 'GURUL', 'GÚNÁR', 'GÚNYA', 'GÜGYE', 'GYALU', 'GYANÚ', 'GYAUR', 'GYÁRI',
        'GYÁRT', 'GYÁSZ', 'GYÁVA', 'GYERE', 'GYORS', 'GYÓGY', 'GYÓNÓ', 'GYŐZŐ', 'GYUFA', 'GYÚJT', 'GYÚRÓ', 'GYÚRT', 'GYŰJT', 'GYŰRT',
        'GYŰRŰ'
    ],
    'H': [
        'HABAR', 'HABÁR', 'HABOS', 'HADAR', 'HADÚR', 'HAIKU', 'HAJAS', 'HAJDÚ', 'HAJÍT', 'HAJOL', 'HAJÓS', 'HAJRÁ', 'HAJTÓ', 'HAJTŰ',
        'HAKNI', 'HALAD', 'HALAS', 'HALÁL', 'HALLÓ', 'HALOM', 'HALŐR', 'HALVA', 'HAMAR', 'HAMIS', 'HANEM', 'HANGA', 'HANTA', 'HAPCI',
        'HAPSI', 'HARAP', 'HARAG', 'HARCI', 'HASAD', 'HASAL', 'HASAS', 'HASÁB', 'HASIS', 'HASÍT', 'HASON', 'HATAN', 'HATÁR', 'HATÁS',
        'HATOD', 'HATOL', 'HATOS', 'HATUK', 'HAVAS', 'HAVER', 'HAZAI', 'HAZUG', 'HÁJAS', 'HÁLÁS', 'HÁLÓS', 'HÁLÓZ', 'HÁMOZ', 'HÁNCS',
        'HÁPOG', 'HÁREM', 'HÁRFA', 'HÁRÍT', 'HÁROM', 'HÁRUL', 'HÁTAS', 'HÁTHA', 'HÁTRA', 'HÁTSÓ', 'HÁTUL', 'HÁZAL', 'HÁZAS', 'HEBEG',
        'HEGED', 'HEGES', 'HEGYI', 'HEKUS', 'HELLÓ', 'HELYI', 'HENYE', 'HERÉL', 'HETED', 'HETEN', 'HETES', 'HEVER', 'HEVES', 'HEVÍT',
        'HEVÜL', 'HÉBER', 'HÉDER', 'HÉJAS', 'HÉTFŐ', 'HÉVÍZ', 'HÉZAG', 'HIÁBA', 'HIÁNY', 'HIBÁS', 'HIDEG', 'HIDRA', 'HIÉNA', 'HIMLŐ',
        'HINDI', 'HINDU', 'HINTA', 'HINTÓ', 'HIPPI', 'HITEL', 'HITES', 'HITHŰ', 'HÍDFŐ', 'HÍGÍT', 'HÍGUL', 'HÍJÁN', 'HÍMES', 'HÍMEZ',
        'HÍNÁR', 'HÍREK', 'HÍRES', 'HÍVAT', 'HÍVÁS', 'HÍVEN', 'HÍZÁS', 'HÍZIK', 'HOBBI', 'HOLLÓ', 'HOLMI', 'HOMÁR', 'HOMOK', 'HONOL',
        'HONFI', 'HONOL', 'HONOS', 'HONŐR', 'HOPPÁ', 'HORDA', 'HORDÓ', 'HOROG', 'HOSSZ', 'HOTEL', 'HOZAM', 'HOZAT', 'HOZÁS', 'HOZZÁ',
        'HÓDÍT', 'HÓDOL', 'HÓEKE', 'HÓHÉR', 'HÓNAP', 'HÖLGY', 'HÖRGŐ', 'HÖRÖG', 'HŐFOK', 'HŐKÖL', 'HŐSÉG', 'HŐSNŐ', 'HŐTAN', 'HUHOG',
        'HULLA', 'HUMÁN', 'HUMOR', 'HURKA', 'HUROK', 'HURRÁ', 'HURUT', 'HUZAL', 'HUZAM', 'HUZAT', 'HÚZÁS', 'HÚROS', 'HÚROZ', 'HÚSOS',
        'HÚZÓS', 'HÜLLŐ', 'HÜLYE', 'HŰBÉR', 'HŰDÉS', 'HŰLÉS', 'HŰLIK', 'HŰSÉG', 'HŰSÍT', 'HŰSÖL', 'HŰTÉS', 'HŰVÖS'
    ],
    'I': [
        'IÁZÁS', 'IÁZIK', 'IBRIK', 'IDÁIG', 'IDEAD', 'IDEÁL', 'IDEÁT', 'IDEÉR', 'IDEGI', 'IDEJE', 'IDEÚT', 'IDÉBB', 'IDÉNY', 'IDILL',
        'IDŐSB', 'IDÜLT', 'IFJÚI', 'IGAZI', 'IGETŐ', 'IGÉNY', 'IGÉZŐ', 'IHATÓ', 'IHLET', 'IJEDT', 'IKRÁS', 'IKTAT', 'ILLAN', 'ILLAT',
        'ILLEM', 'ILLET', 'ILLIK', 'ILYEN', 'IMÁDÓ', 'IMÁGÓ', 'IMÁZS', 'IMÉNT', 'IMMÁR', 'IMOLA', 'INDEX', 'INDÍT', 'INDOK', 'INDUL',
        'INDUS', 'INGAT', 'INGÁS', 'INGER', 'INNEN', 'INPUT', 'INTÉS', 'INTÉZ', 'INTIM', 'IPARI', 'IRÁNY', 'IRÁNT', 'IRIGY', 'IRKÁL',
        'IRODA', 'IRTÁS', 'ISLER', 'ISMER', 'ISMÉT', 'ISPÁN', 'ISTEN', 'ISZAP', 'ISZÁK', 'ISZIK', 'ITATÓ', 'ITTAS', 'ITTEN', 'ITYEG',
        'IVÓLÉ', 'IVRIT', 'IZÉKE', 'IZGAT', 'IZGUL', 'IZMOS', 'IZMUS', 'IZZAD', 'IZZÁS', 'IZZIK', 'IZZÍT'
    ],
    'Í': [
        'ÍBISZ', 'ÍJÁSZ', 'ÍJHÚR', 'ÍNSÉG', 'ÍRISZ', 'ÍRMAG', 'ÍRNOK', 'ÍROTT', 'ÍRÓNŐ', 'ÍTÉSZ', 'ÍVELT', 'ÍZELT', 'ÍZLEL', 'ÍZLÉS',
        'ÍZLIK'
    ],
    'J': [
        'JACHT', 'JAKUT', 'JAPÁN', 'JAVAK', 'JAVÍT', 'JAVUL', 'JÁRAT', 'JÁRÁS', 'JÁRDA', 'JÁRMŰ', 'JÁROM', 'JÁRŐR', 'JÁRUL', 'JÁTÉK',
        'JEGEL', 'JEGES', 'JELEL', 'JELEN', 'JELES', 'JELEZ', 'JELÖL', 'JELZŐ', 'JENKI', 'JÉGER', 'JÉNAI', 'JÉRCE', 'JOGAR', 'JOGOS',
        'JOKER', 'JÓDLI', 'JÓDOS', 'JÓDOZ', 'JÓÍZŰ', 'JÓKOR', 'JÓLÉT', 'JÓMÓD', 'JÓSÁG', 'JÓSDA', 'JÓSNŐ', 'JÓSOL', 'JÓVAL', 'JÓZAN',
        'JÖVET', 'JUHAR', 'JUHOS', 'JUKKA', 'JURTA', 'JUTÁS'
    ],
    'K': [
        'KABÁT', 'KABIN', 'KACAG', 'KACAJ', 'KACAT', 'KACÉR', 'KACSA', 'KACSÓ', 'KADÉT', 'KAJAK', 'KAJÁL', 'KAJÁN', 'KAJLA', 'KAJÜT',
        'KAKAÓ', 'KAKAS', 'KAKÁL', 'KAKIL', 'KALAP', 'KALÓZ', 'KAMAT', 'KAMPÓ', 'KAMRA', 'KANÁL', 'KANCA', 'KANKÓ', 'KANNA', 'KANOS',
        'KANÓC', 'KANÜL', 'KAPAR', 'KAPÁL', 'KAPÁS', 'KAPCA', 'KAPOR', 'KAPÓS', 'KAPUS', 'KARAJ', 'KARÁM', 'KARÁT', 'KARÉJ', 'KARFA',
        'KARMA', 'KAROL', 'KAROM', 'KARÓS', 'KARÓZ', 'KARTA', 'KASPÓ', 'KASZA', 'KASZT', 'KATÓD', 'KAVAR', 'KAZAH', 'KAZAL', 'KAZÁN',
        'KÁBEL', 'KÁBÍT', 'KÁBUL', 'KÁDAS', 'KÁDÁR', 'KÁDER', 'KÁNON', 'KÁNYA', 'KÁOSZ', 'KÁROG', 'KÁROS', 'KÁSÁS', 'KÁTYÚ', 'KÁVÉS',
        'KEBEL', 'KEDDI', 'KEFÉL', 'KEFÍR', 'KEKSZ', 'KELET', 'KELÉS', 'KELLŐ', 'KELME', 'KELTA', 'KELTŐ', 'KENCE', 'KENDŐ', 'KENET',
        'KENÉS', 'KEREK', 'KERES', 'KERET', 'KERÉK', 'KERGE', 'KERÍT', 'KERTI', 'KERUB', 'KERÜL', 'KETTÉ', 'KETTŐ', 'KEVER', 'KEVÉS',
        'KEZDŐ', 'KEZEL', 'KEZES', 'KEZEZ', 'KÉGLI', 'KÉJES', 'KÉJNŐ', 'KÉKES', 'KÉKÍT', 'KÉKÜL', 'KÉMIA', 'KÉMNŐ', 'KÉNES', 'KÉNEZ',
        'KÉNKŐ', 'KÉPES', 'KÉPEZ', 'KÉPZŐ', 'KÉRDŐ', 'KÉREG', 'KÉREM', 'KÉRET', 'KÉRÉS', 'KÉSEI', 'KÉSEL', 'KÉSES', 'KÉSÉS', 'KÉSIK',
        'KÉSŐI', 'KÉSŐN', 'KÉTES', 'KHAKI', 'KIADÓ', 'KIÁLL', 'KIÁLT', 'KIBIC', 'KIBÍR', 'KIBÖK', 'KIBUC', 'KICSI', 'KIDOB', 'KIDŐL',
        'KIDUG', 'KIEJT', 'KIÉLT', 'KIFED', 'KIFEJ', 'KIFEN', 'KIFÉR', 'KIFLI', 'KIFOG', 'KIFŐZ', 'KIFUT', 'KIFÚJ', 'KIFÚR', 'KIFŰT',
        'KIFŰZ', 'KIHAL', 'KIHAT', 'KIHÍV', 'KIHOZ', 'KIHÚZ', 'KIHŰL', 'KIHŰT', 'KIIRT', 'KIJÁR', 'KIJÖN', 'KIJUT', 'KIKAP', 'KIKEL',
        'KIKEN', 'KIKÉR', 'KIKÖP', 'KIKÖT', 'KILÁT', 'KILEL', 'KILES', 'KILÉP', 'KILÉT', 'KILOP', 'KILÓG', 'KILÖK', 'KIMAR', 'KIMER',
        'KIMÉR', 'KIMOS', 'KINCS', 'KINÉZ', 'KINCS', 'KININ', 'KINTI', 'KIOLD', 'KIOLT', 'KIONT', 'KIÖLT', 'KIÖNT', 'KISÍR', 'KIRAK',
        'KIRÁG', 'KIRÁZ', 'KIRÚG', 'KISÍR', 'KISSÉ', 'KISÜL', 'KISÜT', 'KITÁR', 'KITÁT', 'KITÉP', 'KITÉR', 'KITIN', 'KITOL', 'KITÖM',
        'KITÖR', 'KITÚR', 'KITŰZ', 'KIVAN', 'KIVÁG', 'KIVÁJ', 'KIVÁR', 'KIVER', 'KIVET', 'KIVÉD', 'KIVÉS', 'KIVÉT', 'KIVÍV', 'KIVON',
        'KIZÁR', 'KÍGYÓ', 'KÍNAI', 'KÍNÁL', 'KÍNOS', 'KÍNOZ', 'KÍNZÓ', 'KÍSÉR', 'KÍVÁN', 'KÍVÜL', 'KLIKK', 'KLISÉ', 'KLÍMA', 'KOALA',
        'KOBAK', 'KOCKA', 'KOCOG', 'KOCSI', 'KOMÁZ', 'KOMBI', 'KOMLÓ', 'KOMOR', 'KOMÓD', 'KONDA', 'KONDI', 'KONGA', 'KONOK', 'KONTY',
        'KOPÁR', 'KOPÁS', 'KOPIK', 'KOPOG', 'KORAI', 'KORÁL', 'KORÁN', 'KORCS', 'KORDÉ', 'KORHŰ', 'KOROG', 'KOROM', 'KOROS', 'KORPA',
        'KORSÓ', 'KORTY', 'KORZÓ', 'KOSÁR', 'KOSZT', 'KOTON', 'KOTOR', 'KOTTA', 'KOZÁK', 'KÓBOR', 'KÓCOL', 'KÓCOS', 'KÓDEX', 'KÓDOL',
        'KÓKAD', 'KÓMÁS', 'KÓPIA', 'KÓROS', 'KÓRUS', 'KÓSER', 'KÓSZA', 'KÖDÖL', 'KÖDÖS', 'KÖHÖG', 'KÖLES', 'KÖLNI', 'KÖLTŐ', 'KÖNNY',
        'KÖNYV', 'KÖPET', 'KÖPÉS', 'KÖPÜL', 'KÖRBE', 'KÖRET', 'KÖRÍT', 'KÖRÍV', 'KÖRÖM', 'KÖRÖZ', 'KÖRTE', 'KÖRÚT', 'KÖRÜL', 'KÖRZŐ',
        'KÖSZI', 'KÖTEG', 'KÖTET', 'KÖTÉL', 'KÖTÉS', 'KÖTÖZ', 'KÖTVE', 'KÖVES', 'KÖVET', 'KÖVEZ', 'KÖVÉR', 'KÖZBE', 'KÖZEG', 'KÖZEL',
        'KÖZÉP', 'KÖZJÓ', 'KÖZMŰ', 'KÖZÖL', 'KÖZÖS', 'KÖZTE', 'KÖZTI', 'KÖZÚT', 'KÖZÜL', 'KŐFAL', 'KŐKOR', 'KŐLAP', 'KŐPOR', 'KŐZET',
        'KRACH', 'KREÁL', 'KREOL', 'KREPP', 'KRESZ', 'KRÉTA', 'KRIMI', 'KROKI', 'KUCKÓ', 'KUFÁR', 'KUGLI', 'KUJON', 'KUKAC', 'KUKÁS',
        'KUKÁZ', 'KUKTA', 'KULÁK', 'KULCS', 'KUPAC', 'KUPAK', 'KUPEC', 'KUPLÉ', 'KUPON', 'KURTA', 'KURUC', 'KUSZA', 'KUTAS', 'KUTAT',
        'KUTYA', 'KUVIK', 'KÚPOS', 'KÚRÁL', 'KÚRIA', 'KÚTFŐ', 'KÜBLI', 'KÜLDŐ', 'KÜLLŐ', 'KÜLÖN', 'KÜLSŐ', 'KÜRTŐ', 'KÜTYÜ', 'KÜZDŐ',
        'KVARC', 'KVARK', 'KVINT', 'KVITT', 'KVÓTA'
    ],
    'L': [
        'LABDA', 'LABOR', 'LADIK', 'LAGZI', 'LAKAT', 'LAKÁJ', 'LAKÁS', 'LAKIK', 'LAKLI', 'LANKA', 'LAKOL', 'LAKOS', 'LAPÁT', 'LAPÍT',
        'LAPOS', 'LAPOZ', 'LAPUL', 'LASSÚ', 'LATIN', 'LATOR', 'LAVÓR', 'LAZAC', 'LAZÁN', 'LAZÍT', 'LAZUL', 'LÁBAD', 'LÁBAL', 'LÁBAS',
        'LÁBOS', 'LÁGER', 'LÁMPA', 'LÁPOS', 'LÁRMA', 'LÁRVA', 'LÁTÁS', 'LÁZAD', 'LÁZAS', 'LÁZÍT', 'LEÁLL', 'LEÁNY', 'LEBEG', 'LEBŐG',
        'LEBUJ', 'LECKE', 'LECSÓ', 'LEDÉR', 'LEDOB', 'LEDÖF', 'LEDŐL', 'LEEJT', 'LEESZ', 'LEFED', 'LEFEJ', 'LEFOG', 'LEFŐZ', 'LEFUT',
        'LEFÚJ', 'LEFÚR', 'LEFŰZ', 'LEGEL', 'LEHAL', 'LEHEL', 'LEHET', 'LEHÍV', 'LEHOZ', 'LEHÚZ', 'LEHŰL', 'LEHŰT', 'LEINT', 'LEÍRÓ',
        'LEJÁR', 'LEJÖN', 'LEJTŐ', 'LEJUT', 'LEKAP', 'LEKEN', 'LEKÉR', 'LEKÖP', 'LEKÖT', 'LELÁT', 'LELES', 'LELET', 'LELÉP', 'LELÉS',
        'LELKI', 'LELÉP', 'LELÓG', 'LELÖK', 'LEMAR', 'LEMEZ', 'LEMÉR', 'LEMOS', 'LENGE', 'LENGŐ', 'LENÉZ', 'LENGE', 'LENNE', 'LENNI',
        'LENTI', 'LEOLD', 'LEOLT', 'LEÖLT', 'LEÖNT', 'LEPEL', 'LEPKE', 'LEPRA', 'LERAK', 'LERÁG', 'LERÁZ', 'LERÚG', 'LESÓZ', 'LESÜL',
        'LESÜT', 'LETÉP', 'LETÉR', 'LETÉT', 'LETOL', 'LETÖR', 'LETUD', 'LETŰR', 'LETŰZ', 'LEVÁG', 'LEVES', 'LEVER', 'LEVET', 'LEVÉD',
        'LEVÉL', 'LEVON', 'LEZÁR', 'LEZÚZ', 'LÉCEL', 'LÉCES', 'LÉDÚS', 'LÉGIÓ', 'LÉGÚT', 'LÉKEL', 'LÉLEK', 'LÉPES', 'LÉPÉS', 'LÉTRA',
        'LÉZER', 'LIBEG', 'LICIT', 'LICSI', 'LIGER', 'LIGET', 'LIHEG', 'LIKŐR', 'LILÁS', 'LIMIT', 'LISTA', 'LISZT', 'LITER', 'LÍRAI',
        'LOBBI', 'LOBOG', 'LOBOS', 'LOHAD', 'LOHOL', 'LOKÁL', 'LOMHA', 'LOMOL', 'LOMOS', 'LOPÁS', 'LOPVA', 'LOTTÓ', 'LOTYÓ', 'LOVAG',
        'LOVAL', 'LOVAS', 'LÓBÁL', 'LÓDEN', 'LÓDÍT', 'LÓDUL', 'LÓERŐ', 'LÓGAT', 'LÓGÁS', 'LÓGÓS', 'LÓHÚS', 'LÓLÁB', 'LÖKET', 'LÖKÉS',
        'LÖKÖD', 'LÖNCS', 'LÖTTY', 'LÖVEG', 'LÖVET', 'LÖVÉS', 'LŐPOR', 'LŐRÉS', 'LŐTÉR', 'LUDAS', 'LUGAS', 'LUKAS', 'LURKÓ', 'LUSTA',
        'LUTRI', 'LUXUS', 'LÚGOS', 'LÚGOZ', 'LÚMEN'
    ],
    'M': [
        'MACKÓ', 'MACSÓ', 'MADÁR', 'MAFLA', 'MAGAS', 'MAGÁN', 'MAGÁZ', 'MAGMA', 'MAGNÓ', 'MAGOL', 'MAGOS', 'MAGUK', 'MAJOM', 'MAJOR',
        'MAKOG', 'MAKRÓ', 'MALAC', 'MALOM', 'MALŐR', 'MAMBA', 'MAMBÓ', 'MAMUT', 'MANCS', 'MANGA', 'MANGÓ', 'MANKÓ', 'MANNA', 'MAPPA',
        'MARAD', 'MARAT', 'MARÁS', 'MARÉK', 'MARGÓ', 'MARHA', 'MAROK', 'MASNI', 'MASZK', 'MATAT', 'MATEK', 'MATYÓ', 'MÁGIA', 'MÁGUS',
        'MÁJAS', 'MÁJUS', 'MÁKOS', 'MÁLHA', 'MÁLNA', 'MÁMOR', 'MÁNIA', 'MÁRGA', 'MÁRIS', 'MÁRKA', 'MÁRKI', 'MÁRNA', 'MÁSIK', 'MÁSOK',
        'MÁSOL', 'MÁTKA', 'MÁZAS', 'MÁZAZ', 'MÁZLI', 'MÁZOL', 'MÁZSA', 'MECCS', 'MEDÁL', 'MEDDŐ', 'MEDER', 'MEDVE', 'MEGAD', 'MEGÁS',
        'MEGÉG', 'MEGÉL', 'MEGÉR', 'MEGFŐ', 'MEGGY', 'MEGÍR', 'MEGLŐ', 'MEGNŐ', 'MEGÓV', 'MEGÖL', 'MEGRÓ', 'MEGUN', 'MEGÜL', 'MEGÜT',
        'MEGYE', 'MEKEG', 'MELÁK', 'MELEG', 'MELLÉ', 'MELÓS', 'MENÁD', 'MENET', 'MENÉS', 'MENNY', 'MENTA', 'MENTE', 'MENTŐ', 'MENZA',
        'MERED', 'MEREV', 'MERÍT', 'MERRE', 'MERSZ', 'MERÜL', 'MESÉL', 'MESÉS', 'METÁN', 'METÉL', 'METRÓ', 'METSZ', 'MEZEI', 'MÉDIA',
        'MÉGIS', 'MÉGSE', 'MÉHES', 'MÉLÁZ', 'MÉLTÓ', 'MÉNES', 'MÉNKŰ', 'MÉRCE', 'MÉREG', 'MÉRET', 'MÉRÉS', 'MÉTER', 'MÉZES', 'MÉZEZ',
        'MÉZGA', 'MIATT', 'MINTA', 'MIDŐN', 'MIENK', 'MIÉNK', 'MIÉRT', 'MIKOR', 'MIKRÓ', 'MINAP', 'MINEK', 'MINÉL', 'MINTA', 'MIÓMA',
        'MIÓTA', 'MIRHA', 'MIVEL', 'MIXER', 'MILIŐ', 'MÍDER', 'MÍMEL', 'MÍVES', 'MOBIL', 'MODEM', 'MODOR', 'MODUL', 'MOGUL', 'MOHÁS',
        'MOHOS', 'MOHÓN', 'MOKKA', 'MONÁD', 'MONDA', 'MOPED', 'MORAJ', 'MORÁL', 'MOROG', 'MORVA', 'MORZE', 'MOSAT', 'MOSÁS', 'MOSDÓ',
        'MOTEL', 'MOTOR', 'MOTOZ', 'MOTTÓ', 'MOTYÓ', 'MOZGÓ', 'MOZOG', 'MÓDOS', 'MÓKÁS', 'MÓKUS', 'MÓRES', 'MÖGÜL', 'MUFTI', 'MULAT',
        'MULTI', 'MULYA', 'MUMUS', 'MUNGÓ', 'MUNKA', 'MURCI', 'MURIS', 'MURVA', 'MUTAT', 'MUTÁL', 'MUTYI', 'MÚLÁS', 'MÚLIK', 'MÚLVA',
        'MÚMIA', 'MÚZSA', 'MÜZLI', 'MŰBŐR', 'MŰDAL', 'MŰFAJ', 'MŰFOG', 'MŰJÉG', 'MŰLÁB', 'MŰNEM', 'MŰSOR', 'MŰTÉT', 'MŰTŐS', 'MŰSZÓ',
        'MŰTÉT', 'MŰTŐS', 'MŰVEK', 'MŰVEL'
    ],
    'N': [
        'NADÍR', 'NAGYI', 'NAHÁT', 'NAIVA', 'NAHÁT', 'NAJÁD', 'NANDU', 'NAPÉV', 'NAPLÓ', 'NAPOS', 'NARKÓ', 'NATÚR', 'NÁBOB', 'NÁCIÓ',
        'NÁDAS', 'NÁDAZ', 'NÁDOR', 'NÁTHA', 'NEHÉZ', 'NEMDE', 'NEMES', 'NEMEZ', 'NESZE', 'NETÁN', 'NETTÓ', 'NEVEL', 'NEVES', 'NEVET',
        'NEVEZ', 'NEXUS', 'NÉGER', 'NÉHAI', 'NÉHOL', 'NÉMÁN', 'NÉMET', 'NÉPES', 'NÉZET', 'NÉZÉS', 'NÉZVE', 'NIMFA', 'NINCS', 'NÍVÓS',
        'NOHÁT', 'NOMÁD', 'NORMA', 'NOSZA', 'NÓGAT', 'NÓVUM', 'NÖRSZ', 'NÖVEL', 'NÖVÉS', 'NŐIES', 'NŐÍRÓ', 'NŐNAP', 'NŐNEM', 'NŐSÜL',
        'NŐÜGY', 'NŐVÉR', 'NŐZÉS', 'NŐZIK', 'NUDLI', 'NULLA', 'NYLON', 'NYAKI', 'NYÁRI', 'NYÁRS', 'NYELV', 'NYERŐ', 'NYERS', 'NYERT',
        'NYEST', 'NYÉRC', 'NYITÓ', 'NYÍLÓ', 'NYÍLT', 'NYOLC', 'NYUGI', 'NYÚJT', 'NYÚLÓ', 'NYŰTT'
    ],
    'O': [
        'OÁZIK', 'OÁZIS', 'OBOÁS', 'ODAAD', 'ODAÁT', 'ODAÉG', 'ODAÉR', 'ODAÍR', 'ODALŐ', 'ODANŐ', 'ODAÜL', 'ODAÜT', 'ODÁBB', 'ODÁIG',
        'ODÉBB', 'ODVAS', 'OKKER', 'OKOZÓ', 'OKSÁG', 'OKTAT', 'OKTÁN', 'OKTÁV', 'OLASZ', 'OLCSÓ', 'OLDAL', 'OLDAT', 'OLDÁS', 'OLDOZ',
        'OLÍVA', 'OLLÓZ', 'OLTAT', 'OLTÁR', 'OLTÁS', 'OLVAD', 'OLVAS', 'OLYAN', 'OMEGA', 'OMLÁS', 'OMLIK', 'OMLÓS', 'ONNAN', 'ONNÉT',
        'OPCIÓ', 'OPERA', 'OPIÁT', 'ORDAS', 'ORDÍT', 'ORGIA', 'ORIGÓ', 'ORKÁN', 'OROSZ', 'ORROL', 'ORSÓS', 'ORSÓZ', 'ORVOS', 'ORVUL',
        'OSTOR', 'OSTYA', 'OSZTÓ', 'OTTAN'
    ],
    'Ó': [
        'ÓCEÁN', 'ÓCSKA', 'ÓHAJT', 'ÓHAZA', 'ÓKORI', 'ÓKULA', 'ÓLMOS', 'ÓLMOZ', 'ÓNÉRC', 'ÓPIUM', 'ÓRAMŰ', 'ÓRIÁS', 'ÓTVAR', 'ÓVODA',
        'ÓVÓNŐ'
    ],
    'Ö': [
        'ÖBLÍT', 'ÖBLÖS', 'ÖDÉMA', 'ÖKLEL', 'ÖKLÖZ', 'ÖKRÖS', 'ÖLDÖS', 'ÖLELŐ', 'ÖLTÉS', 'ÖMLÉS', 'ÖMLIK', 'ÖNCÉL', 'ÖNERŐ', 'ÖNGÓL',
        'ÖNNÖN', 'ÖNTET', 'ÖNTÉS', 'ÖNTÖZ', 'ÖNVÁD', 'ÖNZÉS', 'ÖRDÖG', 'ÖRVÖS', 'ÖSSZE', 'ÖTÁGÚ', 'ÖTÉVI', 'ÖTFŐS', 'ÖTLET', 'ÖTLIK',
        'ÖTVEN', 'ÖTVÖS', 'ÖTVÖZ'
    ],
    'Ő': [
        'ŐDÖNG', 'ŐRHÁZ', 'ŐRJÍT', 'ŐRLÉS', 'ŐRSÉG', 'ŐRTŰZ', 'ŐRÜLT', 'ŐRZÉS', 'ŐSAPA', 'ŐSERŐ', 'ŐSIDŐ', 'ŐSKOR', 'ŐSZES', 'ŐSZÜL',
        'ŐZBAK', 'ŐZBŐR', 'ŐZHÚS', 'ŐZIKE'
    ],
    'P': [
        'PACAL', 'PACÁK', 'PACÁS', 'PACNI', 'PACSI', 'PADKA', 'PADLÓ', 'PAJOR', 'PAJTA', 'PAJZS', 'PAKLI', 'PAKOL', 'PALÁS', 'PALLÓ',
        'PAKOL', 'PAMPA', 'PAMUT', 'PANCS', 'PANDA', 'PANEL', 'PANÍR', 'PAPÍR', 'PAPOL', 'PAPOS', 'PARAJ', 'PARÉJ', 'PARFÉ', 'PARTI',
        'PASAS', 'PASSZ', 'PATAK', 'PATÁS', 'PATKÓ', 'PAUZA', 'PAZAR', 'PÁCOL', 'PÁCOS', 'PÁLCA', 'PÁLMA', 'PÁLYA', 'PÁNIK', 'PÁPAI',
        'PÁPUA', 'PÁRÁS', 'PÁRIA', 'PÁRKA', 'PÁRNA', 'PÁROL', 'PÁROS', 'PÁRTA', 'PÁRTI', 'PÁTER', 'PECEK', 'PECÉR', 'PEDÁL', 'PEDIG',
        'PELUS', 'PEMPŐ', 'PENGE', 'PENGŐ', 'PEREC', 'PEREG', 'PEREL', 'PEREM', 'PERES', 'PERGŐ', 'PERJE', 'PERON', 'PERTU', 'PETÁK',
        'PETTY', 'PÉLDA', 'PÉPES', 'PIACI', 'PICÚR', 'PIHEG', 'PIHEN', 'PIHÉS', 'PILLA', 'PILLE', 'PINCE', 'PINTY', 'PIÓCA', 'PIPÁL',
        'PIPÁS', 'PIRÍT', 'PIROG', 'PIROS', 'PIRUL', 'PISÁL', 'PISIL', 'PISIS', 'PISZE', 'PITLI', 'PITON', 'PIXEL', 'PIZZA', 'PLACC',
        'PLATÓ', 'PLÁNE', 'PLÁZA', 'PLEXI', 'PLUSZ', 'PLÜSS', 'POCAK', 'POCOK', 'POÉTA', 'POFÁS', 'POFON', 'POFOZ', 'POHÁR', 'POHOS',
        'POKOL', 'POLIP', 'POLKA', 'POMPA', 'PONTY', 'POPSI', 'PORHÓ', 'PORÍT', 'PORNÓ', 'POROL', 'POROS', 'POROZ', 'PORTA', 'PORTÓ',
        'PORZÓ', 'POSTA', 'POSZT', 'POTOM', 'POTYA', 'POZŐR', 'PÓKER', 'PÓLÓS', 'PÓLUS', 'PÓLYA', 'PÓRÁZ', 'PÓRUS', 'PÓTOL', 'PÓZNA',
        'PÓZOL', 'PÖCÖK', 'PÖDÖR', 'PÖFÖG', 'PÖRGŐ', 'PÖRÖG', 'PÖSZE', 'PÖTTY', 'PRÉDA', 'PRÉRI', 'PRÍMA', 'PROCC', 'PROFI', 'PROLI',
        'PRÓBA', 'PRÓZA', 'PUCÉR', 'PUCOL', 'PUCCS', 'PUDLI', 'PUFOG', 'PUFÓK', 'PUHÍT', 'PUHUL', 'PUMPA', 'PUNCS', 'PURDÉ', 'PUSKA',
        'PUSZI', 'PUTRI', 'PUZÓN', 'PÚDER', 'PÚPOS', 'PÚPOZ', 'PÜFÖL', 'PÜLÓN', 'PÜRÉS'
    ],
    'R': [
        'RABBI', 'RABLÓ', 'RABNŐ', 'RABOL', 'RADAR', 'RADÍR', 'RADON', 'RAFIA', 'RAGAD', 'RAGOS', 'RAGOZ', 'RAGYA', 'RAJKÓ', 'RAJTA',
        'RAKAT', 'RAKÁS', 'RANDA', 'RANDI', 'RAPID', 'RAPLI', 'RASSZ', 'RÁÁLL', 'RÁBÍR', 'RÁBÍZ', 'RÁBÖK', 'RÁCIÓ', 'RÁDIÓ', 'RÁDOB',
        'RÁDŐL', 'RÁEJT', 'RÁÉRŐ', 'RÁFÉR', 'RÁFOG', 'RÁFUT', 'RÁFÚJ', 'RÁFŰT', 'RÁFŰZ', 'RÁGÁS', 'RÁGÓS', 'RÁHAT', 'RÁHÚZ', 'RÁJÁR',
        'RÁJÖN', 'RÁKAP', 'RÁKEN', 'RÁKOS', 'RÁKÖP', 'RÁKÖT', 'RÁLÁT', 'RÁLEL', 'RÁLES', 'RÁLÉP', 'RÁLÓG', 'RÁLÖK', 'RÁMÁS', 'RÁMÁZ',
        'RÁMÉR', 'RÁMOL', 'RÁMPA', 'RÁNÉZ', 'RÁÖLT', 'RÁÖNT', 'RÁRAK', 'RÁRÁZ', 'RÁSÓZ', 'RÁSÜL', 'RÁSÜT', 'RÁTÉR', 'RÁTOL', 'RÁTÖR',
        'RÁTŰZ', 'RÁVÁG', 'RÁVER', 'RÁVET', 'RÁVÉS', 'RÁVON', 'RÁZÁS', 'RÁZÓS', 'REBEG', 'RECÉS', 'RECCS', 'REDŐS', 'REDŐZ', 'REGÉL',
        'REGŐS', 'REJLŐ', 'REKED', 'REMEG', 'REMEK', 'REMÉL', 'REMÍZ', 'RENDI', 'REPCE', 'REPED', 'REPES', 'REPÍT', 'REPRÓ', 'REPÜL',
        'RESTI', 'RETEK', 'RETÚR', 'REUMA', 'REVES', 'REZEG', 'REZEL', 'REZES', 'REZGŐ', 'REZSI', 'REZSÓ', 'RÉGEN', 'RÉGIÓ', 'RÉKLI',
        'RÉMES', 'RÉMÍT', 'RÉMÜL', 'RÉTEG', 'RÉTES', 'RÉTOR', 'RÉVÉN', 'RÉVÜL', 'RÉZSŰ', 'RIADÓ', 'RIADT', 'RIDEG', 'RIGLI', 'RIKÍT',
        'RIKSA', 'RITKA', 'RIZSA', 'RÍMEL', 'RÍMES', 'RÍTUS', 'ROBAJ', 'ROBOG', 'ROBOT', 'RODEÓ', 'ROHAD', 'ROHAM', 'ROHAN', 'ROKKA',
        'ROKON', 'ROLÁD', 'ROLNI', 'ROMÁN', 'ROMOS', 'RONCS', 'RONDA', 'RONDÓ', 'RONGY', 'ROPOG', 'ROSTA', 'ROSSZ', 'ROTÁL', 'ROTOR',
        'ROVAR', 'ROVAT', 'ROVÁS', 'RÓDLI', 'RÓZSA', 'RÖFÖG', 'RÖGBI', 'RÖGÖS', 'RÖHEJ', 'RÖHÖG', 'RÖPDE', 'RÖPÍT', 'RÖPKE', 'RÖPÜL',
        'RÖVID', 'RŐZSE', 'RUBEL', 'RUBIN', 'RUGÓS', 'RUGÓZ', 'RUHÁS', 'RUHÁZ', 'RUMBA', 'RUMLI', 'RUMOS', 'RUTIN', 'RÚGÁS', 'RÚGÓS',
        'RÚTUL', 'RÜFKE', 'RÜHES', 'RÜSZT'
    ],
    'S': [
        'SAJÁT', 'SAJGÓ', 'SAJKA', 'SAJOG', 'SAJTÓ', 'SAKÁL', 'SALAK', 'SALSA', 'SANDA', 'SANSZ', 'SAPKA', 'SARAZ', 'SARKI', 'SARLÓ',
        'SAROK', 'SASOL', 'SAVAS', 'SAVAZ', 'SAVÓS', 'SÁFÁR', 'SÁLAS', 'SÁMÁN', 'SÁMFA', 'SÁMLI', 'SÁNTA', 'SÁPAD', 'SÁRGA', 'SÁROS',
        'SÁSKA', 'SÁTÁN', 'SÁTOR', 'SÁVOS', 'SÁVOZ', 'SABAJ', 'SEBES', 'SEBEZ', 'SEGÉD', 'SEGÍT', 'SEHOL', 'SELLŐ', 'SEMMI', 'SENKI',
        'SEPER', 'SEPRŐ', 'SEPRŰ', 'SEREG', 'SERKE', 'SERTE', 'SÉRTŐ', 'SÉTÁL', 'SIKÁL', 'SIKER', 'SIKET', 'SIKÉR', 'SIKÍT', 'SIKLÓ',
        'SILÓZ', 'SIMÁN', 'SIMÍT', 'SIMLI', 'SIMUL', 'SINCS', 'SIPÍT', 'SIPKA', 'SIRAT', 'SIRÁM', 'SISAK', 'SIVÁR', 'SIVÍT', 'SÍBOL',
        'SÍBOT', 'SÍELŐ', 'SÍKOS', 'SÍLÉC', 'SÍPOL', 'SÍPOS', 'SÍRÁS', 'SÍRÓS', 'SÍRKŐ', 'SÍRÓS', 'SÍZÉS', 'SÍZIK', 'SKALP', 'SKÁLA',
        'SKICC', 'SLÁJM', 'SLEJM', 'SLEPP', 'SLICC', 'SLUKK', 'SMACI', 'SMAFU', 'SMINK', 'SMUKK', 'SNITT', 'SODOR', 'SOFŐR', 'SOKAN',
        'SOMFA', 'SONKA', 'SORBA', 'SOROL', 'SOROS', 'SOROZ', 'SÓDER', 'SÓGOR', 'SÓGUN', 'SÓHAJ', 'SÓHER', 'SÓLYA', 'SÓSAV', 'SÓSKA',
        'SÓSTÓ', 'SÓVÁR', 'SÖMÖR', 'SÖPÖR', 'SÖPRŰ', 'SÖRÉT', 'SÖRÖS', 'SÖRÖZ', 'SÖRTE', 'SÖTÉT', 'SPÁJZ', 'SPEJZ', 'SPÉCI', 'SPICC',
        'SPINÉ', 'SPION', 'SPÓRA', 'SPORT', 'SPRŐD', 'SPURI', 'STAND', 'START', 'STÓLA', 'SUDÁR', 'SUFNI', 'SUGÁR', 'SUHAN', 'SUHOG',
        'SUMÁK', 'SUMMA', 'SUNYI', 'SUSOG', 'SUNYI', 'SUSOG', 'SUTTY', 'SÚGÁS', 'SÚROL', 'SÜGÉR', 'SÜKET', 'SÜLDŐ', 'SÜLÉS', 'SÜLLŐ',
        'SÜRGŐ', 'SÜRÖG', 'SÜTÉS', 'SÜVEG', 'SÜVÍT', 'SŰRÍT', 'SŰRŰN', 'SVUNG', 'SZABÓ', 'SZAFT', 'SZAKI', 'SZARU', 'SZARV', 'SZÁLL',
        'SZÁNÓ', 'SZÁNT', 'SZÁRÚ', 'SZÁSZ', 'SZEDŐ', 'SZEGY', 'SZELŐ', 'SZENT', 'SZERB', 'SZERV', 'SZESZ', 'SZETT', 'SZEXI', 'SZÉNA',
        'SZÉRŰ', 'SZIKE', 'SZINT', 'SZIRT', 'SZITA', 'SZÍNI', 'SZÍNŰ', 'SZÍVÓ', 'SZLÁV', 'SZLÖM', 'SZMOG', 'SZNOB', 'SZOBA', 'SZOMJ',
        'SZÓDA', 'SZÓFA', 'SZÓJA', 'SZÓLÓ', 'SZÓRT', 'SZÓSZ', 'SZÓTŐ', 'SZÖKŐ', 'SZÖRF', 'SZÖRP', 'SZÖSZ', 'SZÖVŐ', 'SZŐKE', 'SZŐLŐ',
        'SZŐTT', 'SZTÁR', 'SZTÉK', 'SZUMÓ', 'SZURI', 'SZUSZ', 'SZÚRÓ', 'SZÚRT', 'SZÜGY', 'SZÜLŐ', 'SZŰCS', 'SZŰRŐ', 'SZŰRT', 'SZŰZI'
    ],
    'T': [
        'TABLÓ', 'TACCS', 'TACSI', 'TAGAD', 'TAGOL', 'TAJGA', 'TAKAR', 'TALAJ', 'TALÁL', 'TALÁN', 'TALÁR', 'TALMI', 'TALON', 'TANÁR',
        'TANGÓ', 'TANÉV', 'TANGA', 'TANGÓ', 'TANÍT', 'TANTI', 'TANUL', 'TANYA', 'TAPAD', 'TAPIZ', 'TAPÍR', 'TAPLÓ', 'TAPOS', 'TARAJ',
        'TARÉJ', 'TARJA', 'TARKA', 'TARKÓ', 'TARLÓ', 'TAROL', 'TARTÓ', 'TASAK', 'TASLI', 'TATÁR', 'TAVAS', 'TAXIS', 'TÁBLA', 'TÁBOR',
        'TÁGAS', 'TÁGÍT', 'TÁGUL', 'TÁJÉK', 'TÁJOL', 'TÁKOL', 'TÁLAL', 'TÁLCA', 'TÁLIB', 'TÁMAD', 'TÁMLA', 'TÁMÍV', 'TÁMLA', 'TÁPOS',
        'TÁPSÓ', 'TÁRCA', 'TÁRGY', 'TÁRNA', 'TÁRÁZ', 'TÁRLÓ', 'TÁRNA', 'TÁROL', 'TÁRUL', 'TÁSKA', 'TÁTOG', 'TÁVHŐ', 'TÁVOL', 'TEAFŰ',
        'TEÁZÓ', 'TEGEZ', 'TEHÁT', 'TEHER', 'TEHÉN', 'TEJEL', 'TEJES', 'TEKER', 'TEKNŐ', 'TELEK', 'TELEL', 'TELEP', 'TELEX', 'TELÉR',
        'TELIK', 'TELÍT', 'TEMET', 'TEMPÓ', 'TENOR', 'TEPER', 'TEPSI', 'TEREL', 'TEREM', 'TEREP', 'TERÍT', 'TERMŐ', 'TESTI', 'TESZT',
        'TETEM', 'TEVÉS', 'TETET', 'TETÉZ', 'TÉGLA', 'TÉPÉS', 'TÉRÍT', 'TÉRÜL', 'TÉTEL', 'TÉTET', 'TÉVED', 'TÉVES', 'TÉVÉS', 'TÉVÚT',
        'TÉZIS', 'TIARA', 'TILOS', 'TILTÓ', 'TIMSÓ', 'TINCS', 'TINTA', 'TIPEG', 'TIPLI', 'TIPOR', 'TISZT', 'TITÁN', 'TITOK', 'TIZED',
        'TÍMÁR', 'TÍPUS', 'TÍZEN', 'TÍZES', 'TOBOZ', 'TOJÁS', 'TOJIK', 'TOKÁS', 'TOKOS', 'TOLAT', 'TOLÁS', 'TOMPA', 'TONIK', 'TONNA',
        'TOPIS', 'TOPOG', 'TORMA', 'TORNA', 'TOROK', 'TORTA', 'TORZÓ', 'TOTEM', 'TÓCSA', 'TÓDÍT', 'TÓDUL', 'TÓNUS', 'TÓSZT', 'TÖBBÉ',
        'TÖBBI', 'TÖKÖL', 'TÖKÖS', 'TÖLGY', 'TÖLTŐ', 'TÖMEG', 'TÖMÉS', 'TÖMÍT', 'TÖMLŐ', 'TÖMÖR', 'TÖMPE', 'TÖREK', 'TÖRÉS', 'TÖRIK',
        'TÖRÖK', 'TÖRÖL', 'TÖRPE', 'TÖRÜL', 'TÖRVE', 'TÖRZS', 'TÖVIG', 'TÖVIS', 'TŐKÉS', 'TŐZEG', 'TRAFÓ', 'TREFF', 'TREND', 'TRÉFA',
        'TRIKÓ', 'TROLI', 'TROLL', 'TROMF', 'TRÜKK', 'TUBÁK', 'TUBUS', 'TUCAT', 'TUDAT', 'TUDÁS', 'TUDÓS', 'TUDTA', 'TUDVA', 'TUJÁS',
        'TUKÁN', 'TULAJ', 'TUMOR', 'TUNYA', 'TURBÓ', 'TURNÉ', 'TUSKÓ', 'TUSOL', 'TUTAJ', 'TÚLAD', 'TÚLÉL', 'TÚLLŐ', 'TÚLNŐ', 'TÚLOZ',
        'TÚLSÓ', 'TÚLZÓ', 'TÚRÁS', 'TÚRÓS', 'TÚZOK', 'TÜKÖR', 'TÜNDE', 'TÜNET', 'TÜSKE', 'TÜSZŐ', 'TÜZEL', 'TÜZES', 'TÜZÉR', 'TŰNÉS',
        'TŰNIK', 'TŰRÉS', 'TŰZÉS', 'TŰZKŐ'
    ],
    'U': [
        'UDVAR', 'UGRAT', 'UGRÁL', 'UGRÁS', 'UGRIK', 'UGYAN', 'UJJAS', 'UKRÁN', 'UNCIA', 'UNDOK', 'UNDOR', 'UNOKA', 'UNOTT', 'UNTAT',
        'UNTIG', 'USZÍT', 'UTAZÓ', 'UTÁNA', 'UTÁNI', 'UTCAI', 'UTÓBB', 'UTÓÍZ', 'UVULA'
    ],
    'Ú': [
        'ÚGYIS', 'ÚGYSE', 'ÚJABB', 'ÚJBÓL', 'ÚJÉVI', 'ÚJÍTÓ', 'ÚJKOR', 'ÚJONC', 'ÚJRÁZ', 'ÚJSÁG', 'ÚJULT', 'ÚRINŐ', 'ÚSZÁS', 'ÚSZIK',
        'ÚTADÓ', 'ÚTDÍJ', 'ÚTZÁR'
    ],
    'Ü': [
        'ÜDÍTŐ', 'ÜDÜLŐ', 'ÜDVÖS', 'ÜGETŐ', 'ÜGYEL', 'ÜGYES', 'ÜKAPA', 'ÜLDÖZ', 'ÜLNÖK', 'ÜLŐKE', 'ÜLTET', 'ÜNNEP', 'ÜREGI', 'ÜRMÖS',
        'ÜRÜGY', 'ÜSTÖK', 'ÜSZÖG', 'ÜSZÖK', 'ÜTLEG', 'ÜTŐÉR', 'ÜVÖLT', 'ÜZEMI', 'ÜZLET'
    ],
    'Ű': [
        'ŰZÖTT', 'ŰRLAP'
    ],
    'V': [
        'VACAK', 'VACOG', 'VACOK', 'VADAS', 'VADÍT', 'VADLÓ', 'VADON', 'VADÓC', 'VADŐR', 'VADUL', 'VAGON', 'VAJAS', 'VAJAZ', 'VAJDA',
        'VAJMI', 'VAJON', 'VAKAR', 'VAKÍT', 'VAKOL', 'VAKON', 'VAKSI', 'VAKUL', 'VALÓS', 'VARAS', 'VARGA', 'VARJÚ', 'VASAL', 'VASAS',
        'VASMŰ', 'VASÚT', 'VATTA', 'VÁDLI', 'VÁDLÓ', 'VÁDOL', 'VÁGAT', 'VÁGÁS', 'VÁGTA', 'VÁJAT', 'VÁJÁR', 'VÁJÁS', 'VÁLÁS', 'VÁLIK',
        'VÁLTÓ', 'VÁLYÚ', 'VÁMOL', 'VÁMOS', 'VÁRAT', 'VÁROS', 'VÁRÚR', 'VÁSÁR', 'VÁSIK', 'VÁZOL', 'VEDEL', 'VEDER', 'VEGYI', 'VEKNI',
        'VELŐS', 'VELÚR', 'VEREM', 'VERES', 'VERET', 'VERÉB', 'VERÉS', 'VESÉS', 'VESÉZ', 'VESZT', 'VETÉL', 'VETÉS', 'VETÍT', 'VEZET',
        'VEZÉR', 'VEZÍR', 'VÉDÉS', 'VÉGES', 'VÉGEZ', 'VÉGIG', 'VÉGRE', 'VÉGSŐ', 'VÉGÜL', 'VÉNÁS', 'VÉNÜL', 'VÉRBŐ', 'VÉREB', 'VÉRES',
        'VÉRÉR', 'VÉRZŐ', 'VÉSET', 'VÉSÉS', 'VÉTEK', 'VÉTEL', 'VÉTÉS', 'VÉZNA', 'VIASZ', 'VIDÁM', 'VIDEÓ', 'VIDÉK', 'VIDÍT', 'VIDRA',
        'VIDUL', 'VIGAD', 'VIGÉC', 'VIHAR', 'VIHOG', 'VILÁG', 'VILLA', 'VIOLA', 'VIRÁG', 'VIRÍT', 'VIRUL', 'VISEL', 'VISÍT', 'VISKÓ',
        'VITAT', 'VITÁS', 'VITEL', 'VITET', 'VITÉZ', 'VIZEL', 'VIZES', 'VIZEZ', 'VIZIT', 'VÍGAN', 'VÍRUS', 'VÍVÁS', 'VÍZIÓ', 'VÍZKŐ',
        'VÍZUM', 'VOKÁL', 'VOLÁN', 'VOLNA', 'VONAL', 'VONAT', 'VONÁS', 'VONÍT', 'VONÓS', 'VONUL', 'VONZÓ', 'VÖDÖR', 'VÖLGY', 'VÖRÖS'
    ],
    'Z': [
        'ZABÁL', 'ZABLA', 'ZABOS', 'ZAFÍR', 'ZAJLÓ', 'ZAJOS', 'ZAMAT', 'ZANZA', 'ZAVAR', 'ZÁLOG', 'ZÁPOR', 'ZÁRAS', 'ZÁRÁS', 'ZÁRDA',
        'ZÁRKA', 'ZÁROL', 'ZÁROS', 'ZÁRUL', 'ZÁRVA', 'ZÁVÁR', 'ZEBRA', 'ZEFÍR', 'ZENEI', 'ZENÉL', 'ZENÉS', 'ZENGŐ', 'ZENIT', 'ZERGE',
        'ZÉRUS', 'ZIHÁL', 'ZILÁL', 'ZIZEG', 'ZOKNI', 'ZOKOG', 'ZOKON', 'ZÖMÖK', 'ZÖNGE', 'ZÖREJ', 'ZÖRÖG', 'ZUBOG', 'ZÚDÍT', 'ZÚDUL',
        'ZSEPI', 'ZUBOG', 'ZUHAN', 'ZUHOG', 'ZUTTY', 'ZUZMÓ', 'ZÚGÁS', 'ZÚZÁS', 'ZÚZDA', 'ZŰRÖS', 'ZSABÓ', 'ZSALU', 'ZSARU', 'ZSÁBA',
        'ZSELÉ', 'ZSENI', 'ZSIDÓ', 'ZSOKÉ', 'ZSOLD', 'ZSONG', 'ZSUGA', 'ZSŰRI'
    ]
};
